# -*- coding: utf-8 -*-
"""Customer Churn .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nQUoW0QPmpcORSP_HhLAH-siLMokPaYb
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

np.random.seed(42)
n = 10000
df = pd.DataFrame({
    "Patient_ID": range(1, n+1),
    "Age": np.random.randint(20, 81, n),
    "Gender": np.random.choice(["Male", "Female"], n),
    "Blood_Pressure": np.random.randint(80, 181, n),
    "Sugar_Level": np.random.randint(70, 201, n),
    "Cholesterol": np.random.randint(150, 301, n),
    "Heart_Rate": np.random.randint(60, 121, n)
})

df.head()

df.isnull().sum()

df.info()

df.describe()

df.mean(numeric_only=True)

df.median(numeric_only=True)

df["Gender"].mode()

df.std(numeric_only=True)

def bp_category(bp):
    if bp < 120:
        return "Normal"
    elif bp < 140:
        return "Elevated"
    else:
        return "High"

df["BP_Status"] = df["Blood_Pressure"].apply(bp_category)
print(df["BP_Status"].value_counts())

def sugar_category(s):
    if s < 100:
        return "Normal"
    elif s < 140:
        return "Pre-Diabetic"
    else:
        return "Diabetic"

df["Sugar_Status"] = df["Sugar_Level"].apply(sugar_category)
print(df["Sugar_Status"].value_counts())

def chol_category(c):
    if c < 200:
        return "Normal"
    elif c < 240:
        return "Borderline"
    else:
        return "High"

df["Chol_Status"] = df["Cholesterol"].apply(chol_category)
print(df["Chol_Status"].value_counts())

print("Average Heart Rate:", df["Heart_Rate"].mean())

def risk_score(row):
    score = 0

    if row["Blood_Pressure"] > 140:
        score += 1
    if row["Sugar_Level"] > 140:
        score += 1
    if row["Cholesterol"] > 240:
        score += 1
    if row["Heart_Rate"] > 100 or row["Heart_Rate"] < 60:
        score += 1

    return score


df["Risk_Score"] = df.apply(risk_score, axis=1)
def risk_level(score):
    if score == 0:
        return "Low"
    elif score <= 2:
        return "Medium"
    else:
        return "High"
df["Risk_Level"] = df["Risk_Score"].apply(risk_level)
print(df[["Risk_Score", "Risk_Level"]].head())

high_risk_patients = df[df["Risk_Level"] == "High"]
print(high_risk_patients.head())

bins = [20, 30, 40, 50, 60, 70, 80]
labels = ["20-30", "30-40", "40-50", "50-60", "60-70", "70-80"]

df["Age_Group"] = pd.cut(df["Age"], bins=bins, labels=labels)

print(pd.crosstab(df["Age_Group"], df["BP_Status"]))

print(df.groupby("Gender")[["Blood_Pressure", "Sugar_Level", "Cholesterol", "Heart_Rate"]].mean())

print(df["Risk_Level"].value_counts())

plt.scatter(df["Age"], df["Blood_Pressure"])
plt.title("Blood Pressure vs Age")
plt.xlabel("Age")
plt.ylabel("Blood Pressure")
plt.show()

plt.scatter(df["Cholesterol"], df["Heart_Rate"])
plt.title("Cholesterol vs Heart Rate")
plt.xlabel("Cholesterol")
plt.ylabel("Heart Rate")
plt.show()

df.groupby("Risk_Level")["Sugar_Level"].mean().plot(kind='bar')
plt.title("Sugar Level vs Risk Category")
plt.xlabel("Risk Level")
plt.ylabel("Average Sugar Level")
plt.show()

df["Risk_Level"].value_counts().plot(kind='bar')
plt.title("Risk Level Distribution")
plt.xlabel("Risk Level")
plt.ylabel("Count")
plt.show()

df["Gender"].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Gender Distribution")
plt.ylabel("")
plt.show()

plt.hist(df["Blood_Pressure"], bins=30)
plt.title("Blood Pressure Distribution")
plt.xlabel("BP")
plt.ylabel("Frequency")
plt.show()

plt.scatter(df["Age"], df["Cholesterol"])
plt.title("Age vs Cholesterol")
plt.xlabel("Age")
plt.ylabel("Cholesterol")
plt.show()

plt.boxplot(df["Sugar_Level"])
plt.title("Sugar Level Box Plot")
plt.ylabel("Sugar Level")
plt.show()

import seaborn as sns

corr = df.corr(numeric_only=True)
sns.heatmap(corr, annot=True)
plt.title("Correlation Heatmap")
plt.show()

"""This project demonstrates how synthetic healthcare data can be analyzed using EDA techniques to identify patterns, relationships, and high-risk patients. Visualization tools such as heatmaps, histograms, and scatter plots help in understanding the data effectively. The system supports early detection of health risks, improves patient monitoring, and enables better healthcare decision-making."""